# -*- coding: utf-8 -*-
"""handwritten_digit_recognition_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XpPszZTjz0nNpgkbKU-rIhztcde2LNax
"""

import tensorflow as tf
from tensorflow.keras.models import load_model
import numpy as np
import streamlit as st
from PIL import Image, ImageOps

model = load_model('mnist_handwriting_model.keras')

def predict_digit(image):
    image = image.resize((28, 28)).convert('L')
    image = ImageOps.invert(image)
    image = np.array(image).astype('float32') / 255
    image = image.reshape(1, 28, 28, 1)
    prediction = model.predict(image)
    return np.argmax(prediction), max(prediction[0])

st.set_page_config(page_title="Digit Recognition App", page_icon="✍️", layout="centered")
st.markdown("""
    <style>
        .main { background-color: #f5f5f5; }
        .stButton>button { background-color: #4CAF50; color: white; border-radius: 8px; }
        .stFileUploader>label { color: #4CAF50; font-weight: bold; }
    </style>
""", unsafe_allow_html=True)

st.title("🖊️ Handwritten Digit Recognition")
st.markdown("Upload an image of a handwritten digit (0-9) below, and the model will predict it with confidence.")

uploaded_file = st.file_uploader("Upload a Handwritten Digit Image", type=["png", "jpg", "jpeg"])

if uploaded_file is not None:
    image = Image.open(uploaded_file)
    st.image(image, caption='Uploaded Image', use_column_width=True)
    st.write("Processing the image...")

    digit, confidence = predict_digit(image)

    st.success(f"**Predicted Digit:** {digit}")
    st.info(f"**Confidence:** {confidence * 100:.2f}%")

    st.markdown("""
        <style>
            .success { color: #4CAF50; font-weight: bold; font-size: 18px; }
            .info { color: #2196F3; font-size: 16px; }
        </style>
    """, unsafe_allow_html=True)